const fs = require('fs');
let app = fs.readFileSync('src/App.jsx', 'utf8');

// Find the dossierSaved section: from "{dossierSaved && <>" to the closing "</>}"
// Replace everything between "Dossier ready!" and the closing "</>}" with one button

const readyIdx = app.indexOf('Dossier ready!');
if (readyIdx === -1) {
  console.log('ERROR: "Dossier ready!" not found');
  process.exit(1);
}

// Find the </p> after "Dossier ready!"
const readyLineEnd = app.indexOf('</p>', readyIdx) + 4;

// Find the </>} that closes the dossierSaved block
const closingFragment = app.indexOf('</>}', readyLineEnd);
if (closingFragment === -1) {
  console.log('ERROR: closing </> not found');
  process.exit(1);
}

// Everything between readyLineEnd and closingFragment is the buttons - replace it all
const oldButtons = app.substring(readyLineEnd, closingFragment);
console.log('Removing', oldButtons.split('\n').length, 'lines of old buttons');

const newButton = `

              <button onClick={async () => {
                const file = window._dossierFile;
                if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
                  try {
                    await navigator.share({
                      title: \`Pickup Dossier - \${rental.car || "Vehicle"}\`,
                      text: \`Pickup dossier for \${rental.car || "vehicle"} from \${rental.company || "rental company"}. Generated by RentScan.\`,
                      files: [file],
                    });
                  } catch {}
                } else {
                  const url = URL.createObjectURL(window._dossierBlob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = "RentScan-Dossier-" + (rental.company || "Rental").replace(/\\s+/g, "-") + ".html";
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                  URL.revokeObjectURL(url);
                }
              }} style={{ background: \`linear-gradient(135deg, \${T.accent}, \${T.accent2})\`, color: "#fff", border: "none", borderRadius: "12px", padding: "14px", fontSize: "15px", fontWeight: 700, cursor: "pointer", width: "100%", marginBottom: "8px" }}>
                \u{1F4E4} Save / Share Dossier
              </button>
`;

app = app.substring(0, readyLineEnd) + newButton + app.substring(closingFragment);

fs.writeFileSync('src/App.jsx', app, 'utf8');

// Verify
const hasNewBtn = app.includes('Save / Share Dossier');
const hasShare = app.includes('navigator.share');
const hasFallback = app.includes('a.download');
const hasOldSend = app.includes('Send to rental company');
const hasOldWhatsApp = app.includes('wa.me');
const hasOldSavePdf = app.includes('Save as PDF');

console.log('\nVerification:');
console.log('  Save / Share button:', hasNewBtn ? 'OK' : 'MISSING');
console.log('  Native share:', hasShare ? 'OK' : 'MISSING');
console.log('  Download fallback:', hasFallback ? 'OK' : 'MISSING');
console.log('  Old "Send to rental company":', hasOldSend ? 'STILL THERE' : 'removed');
console.log('  Old WhatsApp:', hasOldWhatsApp ? 'STILL THERE' : 'removed');
console.log('  Old "Save as PDF":', hasOldSavePdf ? 'STILL THERE' : 'removed');

const allGood = hasNewBtn && hasShare && hasFallback && !hasOldSend && !hasOldWhatsApp && !hasOldSavePdf;
console.log(allGood ? '\n=== ALL GOOD ===' : '\n=== ISSUES ===');
